name: Release Resume

on:
  push:
    branches: [main, master]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Convert Markdown to PDF
        uses: BaileyJM02/markdown-to-pdf@v1
        with:
          input_path: src
          output_dir: pdfs
          build_html: false
          build_pdf: true

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ steps.date.outputs.date }}
          name: Resume Release ${{ steps.date.outputs.date }}
          body: |
            Resume updated on ${{ steps.date.outputs.date }}
          files: |
            src/resume.en.md
            src/resume.fr.md
            pdfs/resume.en.pdf
            pdfs/resume.fr.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
